/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.pajeau;

import net.pajeau.WordSearch;

import org.junit.*;
import static org.junit.Assert.*;

import java.io.*;

public class AppTest {
    private static WordSearch myWordSearch;

    @BeforeClass public static void setupTestSession()
    {
        myWordSearch = new WordSearch();
    }

    @Before public void setupOneTest()
    {
        myWordSearch.ResetPuzzle();
    }

    @Test public void wordSearchThrowsIOExceptionIfPuzzleDataIsEmpty() {
        IOException anException = null;

        String anEmptyPuzzle = "";
        StringReader aStringReader = new StringReader(anEmptyPuzzle);

        try
        {
            myWordSearch.importPuzzle(aStringReader);
        }
        catch (IOException e)
        {
            System.out.println(e.getMessage());
            anException = e;
        }

        assertNotNull("No IOException was thrown!", anException);
    }

    @Test public void wordSearchThrowsIOExceptionIfSearchWordsAreShorterThanTwoCharacters() {
        IOException anException = null;

        String anInvalidSearchWordList = "AB,C,DE,FG,HI";
        StringReader aStringReader = new StringReader(anInvalidSearchWordList);

        try
        {
            myWordSearch.importPuzzle(aStringReader);
        }
        catch (IOException e)
        {
            System.out.println(e.getMessage());
            anException = e;
        }

        assertNotNull("No IOException was thrown!", anException);
    }

    @Test public void wordSearchThrowsIOExceptionIfPuzzleGridHasFewerThanTwoLines() {
        IOException anException = null;

        String anInvalidPuzzleGrid = 
            "BONES,KHAN,KIRK,SCOTTY,SPOCK,SULU,UHURA,CHEKOV\n" + 
            "U,M,K,H,U,L,K,I,N,V,J,O,C,W,E\n";

        StringReader aStringReader = new StringReader(anInvalidPuzzleGrid);

        try
        {
            myWordSearch.importPuzzle(aStringReader);
        }
        catch (IOException e)
        {
            System.out.println(e.getMessage());
            anException = e;
        }

        assertNotNull("No IOException was thrown!", anException);
    }
}
