/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.pajeau;

import java.io.*;

public class WordSearchApp {
    public static void main(String[] args) {

        if (args.length < 1)
        {
            // No puzzle file was included on the command line, bail.
            System.out.println("Solves a word search puzzle contained in a text file and outputs the coordinates of the found search words.");
            System.out.println("  JAVA net.pajeau.WordSearchApp <puzzlefile>");
            return;
        }

        try
        {
            FileReader aFileReader = new FileReader(args[0]);
            WordSearch aWordSearch = new WordSearch();

            String aPuzzleSolution = aWordSearch.solvePuzzle(aFileReader);
            System.out.print(aPuzzleSolution);

            aFileReader.close();
        }
        catch (Exception anException)
        {
            System.out.println("An error occurred while processing the puzzle!");
        }
    }
}
